### ISSUE TITLE
Upgrade to new trace.moe API

### ISSUE THREAD

**Issue by soruly** [FeeeeK/TraceMoe_bot#1]
Hi, just want to notify you the new trace.moe API is out.
Please take a look and update your program, otherwise it will be broken when the old API deprecates.
You can find the docs of the new API with migration guide at https://github.com/soruly/trace.moe-api

**Comment by FeeeeK** [comment]
Ok, thanks for the notice, I'll do it  later.

**Comment by FeeeeK** [comment]
By the way, @soruly are you planning to add a new api to swaggerhub?

**Comment by soruly** [comment]
Yes I'm writing one.

**Comment by FeeeeK** [comment]
Ok

**Comment by soruly** [comment]
https://app.swaggerhub.com/apis/soruly/api.trace.moe/1.0.0

**Comment by FeeeeK** [comment]
Thanks, I want to write my own wrapper for api and swaggerhub is helpful for this.
